version: "3"
services:
  res_mplug:
    container_name: res_mplug
    image: res_mplug
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PYTHON_VERSION: python3.8
        TORCH_VERSION: 1.12.1+cu113
        TORCHVISION_VERSION: 0.13.1 

    environment: 
      - NVIDIA_VISIBLE_DEVICES=all 
      - DISPLAY=$DISPLAY
    volumes:
      - ./:/app/
      - /tmp/.X11-unix/:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true # docker run -i  
    tty: true        # docker run -t 
